<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/tasks/task10_numpy_section_3_indexing_%26_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Access the first element of an array.

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0])

1


Access the last element of an array.

In [6]:
print(arr[-1])
print(arr[len(arr)-1])

8
8


Extract first 5 elements from an array.

In [7]:
first5 = arr[0:5]
print(first5)

[1 2 3 4 5]


Extract last 5 elements from an array.

In [8]:
last5 = arr[-6:-1:1]
print(last5)

last52 = arr[-1:-6:-1]
print(last52)

[3 4 5 6 7]
[8 7 6 5 4]


Slice every alternate element.

In [9]:
alt_element = arr[::2]
print(alt_element)

[1 3 5 7]


Reverse an array using slicing.

In [10]:
rev_arr = arr[::-1]
print(rev_arr)

[8 7 6 5 4 3 2 1]


Access a specific row in a matrix.

In [11]:
mtrx = np.matrix(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

print(mtrx[1,:])

[[5 6 7 8]]


Access a specific column in a matrix.

In [12]:
print(mtrx[:,1])

[[2]
 [6]]


Extract a submatrix from a 5×5 matrix.

In [13]:
mtrx2 = np.matrix(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25]
    ]
)

print(mtrx2[1:4,0:3])

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


Replace the third element with value 100.

In [14]:
mtrx2[0,2] = 100
print(mtrx2)

[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


Replace all even numbers with -1.

In [15]:
mtrx2[mtrx2%2 == 0] = -1
print(mtrx2)

[[ 1 -1 -1 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]
 [21 -1 23 -1 25]]


Find all elements greater than 50.

In [25]:
mtrx3 = np.matrix(
    [
        [1,2,30,4,5],
        [6,7,80,9,10],
        [11,12,13,140,150],
        [16,17,18,190,200],
        [21,22,230,24,25]
    ]
)

# gt50 = np.where(mtrx3<50, mtrx3, None)
# print(gt50)

gt50 = mtrx3[mtrx3>50]
print(gt50)

[[ 80 140 150 190 200 230]]


Find indices of elements greater than 50.

In [31]:
rows, cols = np.where(mtrx3>50)
coordinates = list(zip(rows,cols))

print("Rows: ",rows)
print("Cols: ",cols)
print("Indices: ",coordinates)

Rows:  [1 2 2 3 3 4]
Cols:  [2 3 4 3 4 2]
Indices:  [(np.int64(1), np.int64(2)), (np.int64(2), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(4)), (np.int64(4), np.int64(2))]


Select elements divisible by 3.

In [33]:
divby3 = mtrx3[mtrx3%3 == 0]
print(divby3)

[[ 30   6   9  12 150  18  21  24]]


Extract diagonal elements from a matrix.

In [35]:
print(mtrx3.diagonal())

[[  1   7  13 190  25]]
