<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/tasks/task10_numpy_section_1_array_creation_%26_basic_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1: Array Creation & Basic Properties (1-30)

Import the NumPy library and print its version.

In [2]:
import numpy as np

print(np.__version__)

2.0.2


Create a NumPy array containing numbers from 1 to 10.

In [4]:
np_array = np.array(range(1,11))
print(np_array)

[ 1  2  3  4  5  6  7  8  9 10]


Create an array of all zeros with size 10.

In [5]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create an array of all ones with shape (3,3).

In [6]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create an identity matrix of size 5×5.

In [11]:
iden1 = np.eye(N=5, M=None, k=0, dtype=float)
iden2 = np.identity(5)

print(iden1)
print(iden2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create an array of even numbers from 2 to 50.

In [15]:
even_array = np.arange(2,52,2)
print(even_array)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Create an array of odd numbers from 1 to 99.

In [16]:
odd_array = np.arange(1,100,2)
print(odd_array)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


Generate numbers from 10 to 100 with step size 5.

In [17]:
nums = np.arange(10, 101, 5)
print(nums)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


Create a NumPy array from a Python list.

In [18]:
arr = [1,2,3,4,5]
np_arr = np.array(arr)
print(np_arr)

[1 2 3 4 5]


Create a NumPy array from a tuple

In [19]:
arr = (1,2,3,4,5)
tpl_arr = np.array(arr)
print(np_arr)

[1 2 3 4 5]


Find the shape of an array.

In [20]:
array = np.array([2,35,25,2,4])
array.shape

(5,)

Find the dimensions of an array.

In [23]:
array.ndim

1

Find the datatype of array elements

In [26]:
print(type(array))
print(type(array[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


Generate 10 random integers between 1 and 100.

In [28]:


random_arr = np.random.randint(1,101,size=10)
print(random_arr)

[71 86 93 52 81 40 58 64 94 70]


Reshape an array of size 12 into (3,4).

In [29]:
reshaped_arr = np.arange(1,13).reshape(3,4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Flatten a 3×3 matrix into a 1D array.

In [33]:
three_three = np.arange(1,10).reshape(3,3)
print(three_three)

flat = three_three.flatten()
print(flat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


Create a 4×4 matrix filled with value 7.

In [34]:
four_four = np.full((4,4),7)
print(four_four)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


Find the size (number of elements) of an array.

In [35]:
four_four.size

16

Create a diagonal matrix with diagonal values [1,2,3,4].

In [36]:
diagonal = [1,2,3,4]

diag_matrix = np.diag(diagonal)

print(diag_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Convert a float array into an integer array.

In [38]:
float_arr = np.array([1.9, 2.1, 3.7, 4.5])
int_arr = float_arr.astype(int)
print(int_arr)

[1 2 3 4]


Create an array with values between 0 and 1 using linspace().

In [39]:
lin_arr = np.linspace(0,1,10)
print(lin_arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Reverse an array.

In [43]:
print(lin_arr[::-1])
print(np.flip(lin_arr))

[1.         0.88888889 0.77777778 0.66666667 0.55555556 0.44444444
 0.33333333 0.22222222 0.11111111 0.        ]
[1.         0.88888889 0.77777778 0.66666667 0.55555556 0.44444444
 0.33333333 0.22222222 0.11111111 0.        ]


Sort an array in ascending order.

In [44]:
arr = [21,2,5,7,1,65,56]

print(np.sort(arr))

[ 1  2  5  7 21 56 65]


Find the maximum and minimum values in an array.

In [45]:
print(np.min(arr))
print(np.max(arr))

1
65


Find the index of maximum value.

In [48]:
print(np.argmax(arr))

5


Find the index of minimum value.

In [49]:
print(np.argmin(arr))

4


Create a 2×3 matrix and print its transpose.

In [59]:
mtrx = np.matrix(range(1,7)).reshape(2,3)
print(mtrx)
print(mtrx.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Concatenate two arrays.

In [69]:
mtrx2 = np.array(range(1,7))
mtrx3 = np.array(range(7,13))

concated = np.concatenate((mtrx2, mtrx3))

print(concated)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Split an array into 3 equal parts.

In [75]:
parts = np.split(concated,4)
print(parts)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
