<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/tasks/task10_numpy_section_5_intermediate_level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 5: Intermediate Level (81-90)

Generate a random array and normalize it between 0 and 1.

In [1]:
import numpy as np

In [7]:
array = np.array(range(0,9))

min = np.min(array)
max = np.max(array)

normalized_array = (array - min) / (max - min)

print(normalized_array)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


Create a checkerboard pattern matrix (8×8).

In [17]:
checkerboard = np.zeros((8,8), dtype=int)

# print(checkerboard)

checkerboard[1::2,::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Count frequency of each unique value.

In [33]:
array2 = np.random.randint(0,21,10)
print(array2)

values, counts = np.unique(array2, return_counts=True)

frequencies = dict(zip(values.tolist(),counts.tolist()))

print(frequencies)

[15 15  0 14 20 18 11 15 14 15]
{0: 1, 11: 1, 14: 2, 15: 4, 18: 1, 20: 1}


Shuffle elements of an array randomly.

In [37]:
array3 = np.random.randint(0,21,10)
print(array3)

rng = np.random.default_rng()

# creates copy
shuffled_copy = rng.permutation(array3)

# modifies same array
rng.shuffle(array3)

print(array3)
print(shuffled_copy)

[19  9  7 12  4 20 15  0  3 14]
[ 9  7 15 20 12  3 19  0  4 14]
[14  9  4 20 19 12 15  3  7  0]


Find common elements between two arrays.

In [41]:
array4 = np.random.randint(0,50,10)
array5 = np.random.randint(0,50,10)

print(array4)
print(array5)

print(np.intersect1d(array4, array5))

[46  4 10 45 32 15 24 27  4  2]
[ 5 10 18 46 36 44 21 44 34  5]
[10 46]


Remove duplicate values from an array.

In [63]:
# sorted one

array6 = np.random.randint(0,50,10)
print(array6)

sorted_unique_arr = np.unique(array6)
print(sorted_unique_arr)

[46 26 10 15 38 45 45  8 37 46]
[ 8 10 15 26 37 38 45 46]


In [61]:
# without sorting

array6 = np.random.randint(0,50,10)
print(array6)

values, indices = np.unique(array6, return_index=True)

ordered_unique_arr = values[np.argsort(indices)]

print(ordered_unique_arr)

[47 41 18 47 34 17 17 17  1 12]
[47 41 18 34 17  1 12]


Find missing numbers in an array from 1-100.

In [76]:
ten_to_100_all = np.arange(1,101)

# ten_to_100_with_missing = np.random.randint(1,101,97)
ten_to_100_with_missing = np.random.choice(ten_to_100_all, size=97, replace=False)

missing_values = np.setdiff1d(ten_to_100_all, ten_to_100_with_missing)

print(missing_values)

[56 96 99]


Convert a 1D array into a 3D array.

In [82]:
array1d = np.arange(0,16)
print(array1d)

print(array1d.reshape(2,4,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


Create a border matrix where borders are 1 and inner values are 0.

In [84]:
border_matrix = np.ones((8,8), dtype=int)

border_matrix[1:-1:1, 1:-1:1] = 0
print(border_matrix)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
