<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/tasks/task10_numpy_section_2_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 2: Basic Operations (31-50)

Add two arrays element-wise.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

print(arr1 + arr2)

[ 4  6  8 10]


Subtract two arrays element-wise.

In [3]:
print(arr2 - arr1)

[2 2 2 2]


Multiply two arrays element-wise

In [4]:
print(arr1*arr2)

[ 3  8 15 24]


Divide two arrays element-wise.

In [5]:
print(arr1/arr2)

[0.33333333 0.5        0.6        0.66666667]


Find square of every element in an array

In [8]:
print(np.square(arr1))

[ 1  4  9 16]


Find cube of every element.

In [9]:
print(np.pow(arr1,3))

[ 1  8 27 64]


Calculate square root of array values.

In [12]:
print(np.sqrt(np.square(arr1)))

[1. 2. 3. 4.]


Find exponential values of array elements.

In [13]:
print(np.exp(arr1))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


Find logarithm of array elements

In [14]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436]


Compute sum of all elements in an array.

In [15]:
print(np.sum(arr1))

10


Compute mean of array values.

In [16]:
print(np.mean(arr1))

2.5


Compute median of array values.

In [17]:
print(np.median(arr1))

2.5


Compute standard deviation.

In [18]:
print(np.std(arr1))

1.118033988749895


Compute variance.

In [19]:
print(np.var(arr1))

1.25


Find cumulative sum of elements.

In [20]:
print(np.cumsum(arr1))

[ 1  3  6 10]


Find cumulative product of elements.

In [21]:
print(np.cumprod(arr1))

[ 1  2  6 24]


Find product of all elements in array.

In [22]:
print(np.prod(arr1))

24


Round decimal values to 2 decimal places.

In [23]:
arr = np.array([1.23456, 4.8972, 9.001, 16.555, 25.1])

print(np.round(arr,decimals=2))

[ 1.23  4.9   9.   16.56 25.1 ]


Find absolute values of negative numbers.

In [29]:
arr3 = [1,2,-4,6,-7]

print(np.abs(arr3))

[1 2 4 6 7]


Replace all negative values with zero.

In [30]:
print(np.maximum(0, arr3))

[1 2 0 6 0]
