<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/tasks/task10_numpy_section_4_matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 4: Matrix Operations (66-80)

Add two matrices.

In [1]:
import numpy as np

In [3]:
mtrx1 = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15]
    ]
)

mtrx2 = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15]
    ]
)


print(mtrx1 + mtrx2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


Subtract two matrices.

In [4]:
print(mtrx1 - mtrx2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Multiply two matrices element-wise.

In [7]:
print(mtrx1 * mtrx2)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]


Perform matrix multiplication using dot().

In [10]:
mtrx3 = np.array(
    [
        [1,2,3],
        [4,5,6],
    ]
)

mtrx4 = np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)

print(np.dot(mtrx3, mtrx4))

[[22 28]
 [49 64]]


Calculate transpose of a matrix.

In [11]:
print(np.transpose(mtrx3))

[[1 4]
 [2 5]
 [3 6]]


Find determinant of a matrix.

In [24]:
mtrx5 = np.matrix(range(1,10)).reshape(3,3)

print(mtrx5)
print(np.linalg.det(mtrx5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


Find inverse of a matrix.

In [27]:
# A non-singular matrix (determinant will not be 0)
working_matrix = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 0]]) # Changed 9 to 0

print(np.linalg.inv(working_matrix))

[[-1.77777778  0.88888889 -0.11111111]
 [ 1.55555556 -0.77777778  0.22222222]
 [-0.11111111  0.22222222 -0.11111111]]


1.   Find eigenvalues of a matrix.
2.   Find eigenvectors of a matrix.

In [31]:
eigenvalues, eigenvectors = np.linalg.eig(mtrx5)
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues: 
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Compute matrix rank.

In [32]:
print(np.linalg.matrix_rank(mtrx5))

2


Create a random 4×4 matrix and find row sums.

In [44]:
matrix4x4 = np.array(range(0,16)).reshape(4,4)
print(matrix4x4)

print(matrix4x4.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 6 22 38 54]


Find column sums of a matrix.

In [45]:
print(matrix4x4.sum(axis=0))

[24 28 32 36]


Find row-wise maximum values.

In [46]:
print(np.max(matrix4x4, axis=1))

[ 3  7 11 15]


Find column-wise minimum values.

In [47]:
print(np.max(matrix4x4, axis=0))

[12 13 14 15]
