<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/tasks/task10_numpy_section_6_advanced_level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 6: Advanced Level (91-100)

Implement one-hot encoding using NumPy only.

In [2]:
import numpy as np

In [5]:
labels = np.array([0, 2, 1, 0, 2])
num_classes = 3

print(np.eye(num_classes, dtype=int))
print("\n")
onehot = np.eye(num_classes, dtype=int)[labels]

print(onehot)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


[[1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]]
