In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Step 1: Create a synthedic classification data using sklearn
X, y = make_classification(
    n_samples=10,      # Number of samples
    n_features=2,      # Number of features
    n_informative=2,   # Number of informative features
    n_redundant=0,     # Number of redundant features
    n_classes=2,       # Number of classes
    random_state=42    # Number of reproducibility
)

In [5]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [7]:
# Convert the data to pytorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

/var/folders/hg/ybvpz2sd5pxg82v04p1v28w00000gn/T/ipykernel_38843/2195288036.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
/var/folders/hg/ybvpz2sd5pxg82v04p1v28w00000gn/T/ipykernel_38843/2195288036.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.long)


In [8]:
from torch.utils.data import Dataset, DataLoader

#### Dataset

In [26]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [27]:
dataset = CustomDataset(X, y)

In [28]:
len(dataset)

10

In [29]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

#### DataLoader

In [30]:
dataloader = DataLoader(dataset=dataset, batch_size=2, shuffle=True)

In [31]:
for batch_feature, bath_label in dataloader:
    print(batch_feature)
    print(bath_label)
    print('-'*50)

tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.0683, -0.9701]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]])
tensor([1, 1])
--------------------------------------------------


DataLoader important parameters

1. dataset (mandatory)
2. batch_size
3. shuffle
4. num_workers
5. pin_memory
6. drop_last
7. collate_fn
8. sampler