<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/vs-code/pytorch/lstm_next_word_predictor_class_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
!pip install nltk

In [3]:
import pandas as pd
import numpy as np
import nltk
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from collections import Counter

In [4]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
tokens = nltk.word_tokenize(document.lower())

In [6]:
tokens

['about',
 'the',
 'program',
 'what',
 'is',
 'the',
 'course',
 'fee',
 'for',
 'data',
 'science',
 'mentorship',
 'program',
 '(',
 'dsmp',
 '2023',
 ')',
 'the',
 'course',
 'follows',
 'a',
 'monthly',
 'subscription',
 'model',
 'where',
 'you',
 'have',
 'to',
 'make',
 'monthly',
 'payments',
 'of',
 'rs',
 '799/month',
 '.',
 'what',
 'is',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 '?',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 'is',
 '7',
 'months',
 '.',
 'so',
 'the',
 'total',
 'course',
 'fee',
 'becomes',
 '799',
 '*',
 '7',
 '=',
 'rs',
 '5600',
 '(',
 'approx',
 '.',
 ')',
 'what',
 'is',
 'the',
 'syllabus',
 'of',
 'the',
 'mentorship',
 'program',
 '?',
 'we',
 'will',
 'be',
 'covering',
 'the',
 'following',
 'modules',
 ':',
 'python',
 'fundamentals',
 'python',
 'libraries',
 'for',
 'data',
 'science',
 'data',
 'analysis',
 'sql',
 'for',
 'data',
 'science',
 'maths',
 'for',
 'machine',
 'learning',
 'ml',
 'algorithms',
 'p

In [7]:
vocabs = {'UNK': 0}

for token in tokens:
  if token not in vocabs:
    vocabs[token] = len(vocabs)

In [8]:
vocabs

{'UNK': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.in/

In [9]:
len(vocabs)

289

In [10]:
input_sentences = document.split('\n')

In [11]:
len(input_sentences)

78

In [12]:
def text_to_indices(sentence, vocabs):
  indices = []
  for token in nltk.word_tokenize(sentence.lower()):
    if token in vocabs:
      indices.append(vocabs[token])
    else:
      indices.append(vocabs['UNK'])
  return indices

In [13]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(sentence, vocabs))

In [14]:
len(input_numerical_sentences)

78

In [15]:
training_sequences = []

for sentence in input_numerical_sentences:
  for i in range(1, len(sentence)):
    training_sequences.append(sentence[:i+1])

In [16]:
training_sequences[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [17]:
lengths = []

for sequence in training_sequences:
  lengths.append(len(sequence))

max(lengths)

62

In [18]:
len(training_sequences)

942

In [19]:
padded_training_sequences = []

for sequence in training_sequences:
  padded_training_sequences.append([0]*(max(lengths)-len(sequence)) + sequence)

In [20]:
len(padded_training_sequences[1])

62

In [21]:
padded_training_sequences = torch.tensor(padded_training_sequences)

In [22]:
padded_training_sequences

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [23]:
X = padded_training_sequences[:, :-1]
y = padded_training_sequences[:, -1]

In [24]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [25]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [26]:
len(X[0])

61

In [27]:
len(y)

942

In [28]:
class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self, index):
    return self.X[index], self.y[index]

In [29]:
dataset = CustomDataset(X, y)

In [30]:
dataset[25]

(tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  6, 16, 17,
         18, 19, 20, 21, 22, 23, 24]),
 tensor(25))

In [31]:
len(dataset)

942

In [32]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [33]:
class LSTMModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 150, batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, X):
    embeddings = self.embedding(X)
    intermediate_hidden_states, (final_hidden_state, final_cell_state) = self.lstm(embeddings)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [34]:
model = LSTMModel(len(vocabs))

In [35]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

LSTMModel(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [36]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [37]:
# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f'Epoch: {epoch+1}, Avg Loss: {total_loss/len(dataloader)}')

Epoch: 1, Avg Loss: 5.519393444061279
Epoch: 2, Avg Loss: 4.876837460199992
Epoch: 3, Avg Loss: 4.458672483762105
Epoch: 4, Avg Loss: 4.073782356580098
Epoch: 5, Avg Loss: 3.67821253935496
Epoch: 6, Avg Loss: 3.3260125001271565
Epoch: 7, Avg Loss: 2.971002626419067
Epoch: 8, Avg Loss: 2.66110212802887
Epoch: 9, Avg Loss: 2.37519812186559
Epoch: 10, Avg Loss: 2.1273900389671327
Epoch: 11, Avg Loss: 1.8783740878105164
Epoch: 12, Avg Loss: 1.6833336432774861
Epoch: 13, Avg Loss: 1.4783635894457499
Epoch: 14, Avg Loss: 1.3190721114476522
Epoch: 15, Avg Loss: 1.158963112036387
Epoch: 16, Avg Loss: 1.0177997589111327
Epoch: 17, Avg Loss: 0.9070362587769826
Epoch: 18, Avg Loss: 0.8070898095766703
Epoch: 19, Avg Loss: 0.7135268410046895
Epoch: 20, Avg Loss: 0.6436968247095743
Epoch: 21, Avg Loss: 0.5786601305007935
Epoch: 22, Avg Loss: 0.5259335607290268
Epoch: 23, Avg Loss: 0.4742308735847473
Epoch: 24, Avg Loss: 0.43829980691274006
Epoch: 25, Avg Loss: 0.3942025139927864
Epoch: 26, Avg Loss:

In [38]:
# prediction

def prediction(model, vocabs, sentence):

  device = next(model.parameters()).device

  # text/sentence -> numerical indices
  numerical_text = text_to_indices(sentence, vocabs)

  # padding
  padded_text = torch.tensor([0]*(61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0)

  padded_text = padded_text.to(device)

  # send to model
  output = model(padded_text)

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return sentence + " " + list(vocabs.keys())[index]

In [39]:
prediction(model, vocabs, "What is the course fee for")

'What is the course fee for data'

In [40]:
prediction(model, vocabs, "The course follows a monthly")

'The course follows a monthly subscription'

In [44]:
import time

num_tokens = 10
input_text = "The course follows a monthly"

for i in range(num_tokens):
  output_text = prediction(model, vocabs, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


The course follows a monthly subscription
The course follows a monthly subscription model
The course follows a monthly subscription model where
The course follows a monthly subscription model where you
The course follows a monthly subscription model where you have
The course follows a monthly subscription model where you have to
The course follows a monthly subscription model where you have to make
The course follows a monthly subscription model where you have to make monthly
The course follows a monthly subscription model where you have to make monthly payments
The course follows a monthly subscription model where you have to make monthly payments of


In [45]:
# accuracy
def calculate_accuracy(model, dataloader):

  model.eval()
  total_correct = 0
  total_tokens = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:

      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      output = model(batch_x)

      _, predicted_indices = torch.max(output, dim=1)

      total_correct += (predicted_indices == batch_y).sum().item()
      total_tokens += len(batch_y)

  accuracy = (total_correct / total_tokens) * 100
  return accuracy

In [47]:
# Compute accuracy
accuracy = calculate_accuracy(model, dataloader)
print(f"Model Accuracy: {accuracy:.2f}%")

Model Accuracy: 95.65%
