<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/vs-code/pytorch/tensor_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
device

device(type='cuda')

In [8]:
# creating new tensor in GPU
torch.rand((2,3), device=device)

tensor([[0.2575, 0.0025, 0.9146],
        [0.1968, 0.6030, 0.2794]], device='cuda:0')

In [7]:
a = torch.rand(2,3)
a

tensor([[0.2443, 0.9441, 0.4895],
        [0.5257, 0.5007, 0.2808]])

In [10]:
# moving tensor in GPU
b = a.to(device)

In [11]:
b + 5

tensor([[5.2443, 5.9441, 5.4895],
        [5.5257, 5.5007, 5.2808]], device='cuda:0')

In [14]:
# import torch
import time

# define size of the matrices
size = 1000

# create random matrices
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# calculate time of their multiplication
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication
cpu_time = time.time() - start_time

print("Time taken by the CPU to multiply the matrices: ", cpu_time)

# create random matrices
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# calculate time of their multiplication
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # matrix multiplication
torch.cuda.synchronize() # ensure all GPU operations are complete
gpu_time = time.time() - start_time

print("Time taken by the GPU to multiply the matrices: ", gpu_time)

Time taken by the CPU to multiply the matrices:  0.02017998695373535
Time taken by the GPU to multiply the matrices:  0.0010538101196289062
