In [1]:
import torch

In [2]:
print(torch.__version__)

2.13.0


In [3]:
torch.cuda.is_available()

False

In [5]:
# using empty
a = torch.empty(2, 3)

In [6]:
type(a)

torch.Tensor

In [8]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using randn
torch.randn(2, 3)

tensor([[-0.5151,  1.2377, -1.4717],
        [ 1.8842, -0.8581, -0.3157]])

In [11]:
# using seed
torch.manual_seed(100)
torch.randn(2, 3)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])

In [12]:
torch.manual_seed(100)
torch.randn(2, 3)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])

In [13]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# using arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [15]:
# using linspace
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [16]:
# using eye
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
# using full
torch.full((2, 3), 7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [18]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

### Tensor DataTypes

In [24]:
# find data types of tensor
x.dtype

torch.int64

In [25]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [26]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [28]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations on Tensors

#### 1. Scaler Operation

In [31]:
x = torch.tensor([[1, 2], [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [32]:
x+2

tensor([[3, 4],
        [5, 6]])

In [33]:
x-2

tensor([[-1,  0],
        [ 1,  2]])

In [34]:
x*2

tensor([[2, 4],
        [6, 8]])

In [35]:
x/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [38]:
(x*100) // 3

tensor([[ 33,  66],
        [100, 133]])

In [39]:
# mod
((x*100) // 3) % 2

tensor([[1, 0],
        [0, 1]])

In [40]:
x**2

tensor([[ 1,  4],
        [ 9, 16]])

#### 2. Element-wise Operation

In [41]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [44]:
a + b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [45]:
a - b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [46]:
a * b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [47]:
a / b

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [48]:
a ** b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [49]:
a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [50]:
c = torch.tensor([1, -2, 3, -4])

In [51]:
torch.absolute(c)

tensor([1, 2, 3, 4])

In [52]:
torch.negative(c)

tensor([-1,  2, -3,  4])

In [53]:
# round 
d = torch.tensor([1.2, 2.5, 3.7, 4.1])

In [56]:
torch.round(d)

tensor([1., 2., 4., 4.])

In [57]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [59]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [60]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.5000, 3.0000, 3.0000])

#### 3. Reduction Operation

In [67]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [68]:
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [69]:
torch.sum(e)

tensor(28.)

In [70]:
torch.sum(e, dim=0)

tensor([ 3., 14., 11.])

In [71]:
torch.sum(e, dim=1)

tensor([16., 12.])

In [72]:
torch.mean(e)

tensor(4.6667)

In [73]:
torch.mean(e, dim=0)

tensor([1.5000, 7.0000, 5.5000])

In [74]:
torch.median(e)

tensor(4.)

In [75]:
torch.min(e)

tensor(0.)

In [76]:
torch.max(e)

tensor(9.)

In [77]:
torch.prod(e)

tensor(0.)

In [78]:
torch.std(e)

tensor(3.1411)

In [79]:
torch.var(e)

tensor(9.8667)

In [80]:
torch.argmax(e)

tensor(1)

In [81]:
torch.argmin(e)

tensor(3)

#### 3. Matrix Operation

In [82]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(2,3), low=0, high=10)

In [86]:
torch.matmul(f, g.T)

tensor([[184, 117],
        [164, 127]])

In [88]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [89]:
torch.dot(vector1, vector2)

tensor(11)

In [91]:
torch.transpose(f, 0, 1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [94]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [96]:
torch.det(h)

tensor(-120.)

In [97]:
torch.inverse(h)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01, -6.9539e-09, -1.7500e-01]])

#### 5. Comparison Operation

In [98]:
i = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
j = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [99]:
i > j

tensor([[False,  True, False],
        [ True, False,  True],
        [ True, False,  True]])

In [100]:
i < j

tensor([[False, False, False],
        [False,  True, False],
        [False,  True, False]])

In [103]:
i == j

tensor([[ True, False,  True],
        [False, False, False],
        [False, False, False]])

In [104]:
i != j

tensor([[False,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [105]:
i >= j

tensor([[ True,  True,  True],
        [ True, False,  True],
        [ True, False,  True]])

In [106]:
i <= j

tensor([[ True, False,  True],
        [False,  True, False],
        [False,  True, False]])

#### 6. Speacial Functions

In [108]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [109]:
torch.log(k)

tensor([[1.7918, 0.6931, 2.1972],
        [1.6094,   -inf, 1.3863]])

In [110]:
torch.exp(k)

tensor([[4.0343e+02, 7.3891e+00, 8.1031e+03],
        [1.4841e+02, 1.0000e+00, 5.4598e+01]])

In [111]:
torch.sqrt(k)

tensor([[2.4495, 1.4142, 3.0000],
        [2.2361, 0.0000, 2.0000]])

In [112]:
torch.sigmoid(k)

tensor([[0.9975, 0.8808, 0.9999],
        [0.9933, 0.5000, 0.9820]])

In [113]:
torch.softmax(k, dim=1)

tensor([[4.7385e-02, 8.6788e-04, 9.5175e-01],
        [7.2748e-01, 4.9017e-03, 2.6762e-01]])

In [114]:
torch.relu(k)

tensor([[6., 2., 9.],
        [5., 0., 4.]])

### Inplace Operations

In [115]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [116]:
m + n

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [119]:
# this does not create a new tensor, it modifies the existing tensor m in place
m.add_(n)

tensor([[1.0136, 1.1228, 0.7681],
        [0.8179, 2.0615, 1.3198]])

In [120]:
m

tensor([[1.0136, 1.1228, 0.7681],
        [0.8179, 2.0615, 1.3198]])

In [121]:
m.relu_()

tensor([[1.0136, 1.1228, 0.7681],
        [0.8179, 2.0615, 1.3198]])

In [122]:
m

tensor([[1.0136, 1.1228, 0.7681],
        [0.8179, 2.0615, 1.3198]])

In [123]:
# functionName_ means the inplace operation, just one underscore after function

### Copying a Tensor

In [124]:
a = torch.rand(2, 3)

In [125]:
b = a

In [126]:
a

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [127]:
a[0][0] = 0

In [128]:
a

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [129]:
b

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [130]:
id(a)

4624955856

In [131]:
id(b)

4624955856

In [132]:
b = a.clone()

In [133]:
a

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [134]:
b

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [135]:
a[0][0] = 10

In [136]:
a

tensor([[10.0000,  0.6017,  0.4234],
        [ 0.5224,  0.4175,  0.0340]])

In [137]:
b

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [138]:
id(a)

4624955856

In [139]:
id(b)

4624945536

### Tensor Operation on GPU

In [145]:
# In another file (google colab)

### Reshaping Tensors

In [147]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [149]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [151]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [152]:
b = torch.rand(2,3,4)
b

tensor([[[0.9157, 0.3079, 0.6269, 0.8277],
         [0.6594, 0.0887, 0.4890, 0.5887],
         [0.7340, 0.8497, 0.9112, 0.4847]],

        [[0.9436, 0.3904, 0.2499, 0.3206],
         [0.9753, 0.7582, 0.6688, 0.2651],
         [0.2336, 0.5057, 0.5688, 0.0634]]])

In [154]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [155]:
# unsqueeze
# image
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [156]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

### Numpy vs PyTorch

In [158]:
import numpy as np

In [159]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [160]:
b = a.numpy()
b

array([1, 2, 3])

In [161]:
c = np.array([1,2,3])

In [162]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])