In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand meaning of words',
    'nlp is an interesting topic'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand meaning of words',
 'nlp is an interesting topic']

In [5]:
type(sent)

list

In [6]:
voc_size = 10000

In [7]:
for words in sent:
    print(one_hot(words, voc_size))

[6624, 8311, 2156, 1415]
[6624, 8311, 2156, 914]
[6624, 580, 2156, 6215]
[5525, 450, 5473, 6377, 3511]
[5525, 450, 5473, 6377, 3535]
[302, 8175, 2156, 6545]
[807, 2532, 4708, 1067, 5376]


In [8]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [9]:
one_hot_repr

[[6624, 8311, 2156, 1415],
 [6624, 8311, 2156, 914],
 [6624, 580, 2156, 6215],
 [5525, 450, 5473, 6377, 3511],
 [5525, 450, 5473, 6377, 3535],
 [302, 8175, 2156, 6545],
 [807, 2532, 4708, 1067, 5376]]

In [29]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [16]:
sent_length = 8

In [25]:
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [26]:
embedded_docs

array([[   0,    0,    0,    0, 6624, 8311, 2156, 1415],
       [   0,    0,    0,    0, 6624, 8311, 2156,  914],
       [   0,    0,    0,    0, 6624,  580, 2156, 6215],
       [   0,    0,    0, 5525,  450, 5473, 6377, 3511],
       [   0,    0,    0, 5525,  450, 5473, 6377, 3535],
       [   0,    0,    0,    0,  302, 8175, 2156, 6545],
       [   0,    0,    0,  807, 2532, 4708, 1067, 5376]])

In [27]:
dim = 10

In [30]:
model = Sequential()

In [31]:
model.add(Embedding(voc_size, dim, input_length=sent_length))

In [32]:
model.compile('adam', 'mse')

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 335ms/step


array([[[ 0.04464661,  0.00534686, -0.00551707, -0.02716166,
          0.0399344 , -0.04704688, -0.00021742,  0.03208214,
         -0.01286244, -0.02951932],
        [ 0.04464661,  0.00534686, -0.00551707, -0.02716166,
          0.0399344 , -0.04704688, -0.00021742,  0.03208214,
         -0.01286244, -0.02951932],
        [ 0.04464661,  0.00534686, -0.00551707, -0.02716166,
          0.0399344 , -0.04704688, -0.00021742,  0.03208214,
         -0.01286244, -0.02951932],
        [ 0.04464661,  0.00534686, -0.00551707, -0.02716166,
          0.0399344 , -0.04704688, -0.00021742,  0.03208214,
         -0.01286244, -0.02951932],
        [-0.03998018,  0.00941398,  0.01353893, -0.01089103,
         -0.00533912,  0.04920543, -0.01591084,  0.00214535,
         -0.00962505,  0.04990834],
        [-0.01641058,  0.00627809,  0.00685757, -0.01625655,
         -0.00113469,  0.02826259, -0.03438761, -0.02346592,
          0.01770573, -0.0098428 ],
        [ 0.01778357,  0.02521852,  0.01541376, -0.0

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0, 6624, 8311, 2156, 1415])

In [37]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 77ms/step


array([[ 0.04464661,  0.00534686, -0.00551707, -0.02716166,  0.0399344 ,
        -0.04704688, -0.00021742,  0.03208214, -0.01286244, -0.02951932],
       [ 0.04464661,  0.00534686, -0.00551707, -0.02716166,  0.0399344 ,
        -0.04704688, -0.00021742,  0.03208214, -0.01286244, -0.02951932],
       [ 0.04464661,  0.00534686, -0.00551707, -0.02716166,  0.0399344 ,
        -0.04704688, -0.00021742,  0.03208214, -0.01286244, -0.02951932],
       [ 0.04464661,  0.00534686, -0.00551707, -0.02716166,  0.0399344 ,
        -0.04704688, -0.00021742,  0.03208214, -0.01286244, -0.02951932],
       [-0.03998018,  0.00941398,  0.01353893, -0.01089103, -0.00533912,
         0.04920543, -0.01591084,  0.00214535, -0.00962505,  0.04990834],
       [-0.01641058,  0.00627809,  0.00685757, -0.01625655, -0.00113469,
         0.02826259, -0.03438761, -0.02346592,  0.01770573, -0.0098428 ],
       [ 0.01778357,  0.02521852,  0.01541376, -0.01435087, -0.01314397,
         0.0482332 , -0.00547224,  0.0117057 